# Docker produccion o stage
FROM golang:1.14.3-buster

WORKDIR /go/src/github.com/nmarsollier/resourcesgo
RUN curl -L https://github.com/nmarsollier/resourcesgo/tarball/master | tar xz --strip=1
RUN go install

ENV MONGO_URL mongodb://host.docker.internal:27017

# Puerto de Auth Service
EXPOSE 3000

CMD ["resourcesgo"]

